title: Yixuan (Allison) Gao # your name (or website title) here
logo: "https://github.com/yixuan-gao/yixuan-gao.github.io/blob/master/%E5%A4%B4%E5%83%8F.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  An optimist,
  a fighter,
  an observer
  <br><br>
  <a href="www.linkedin.com/in/yixuan-gao">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
